name: Housing
version: '1.0'
main: com.tommustbe12.housing.Housing
api-version: '1.21'
authors: [ TomMustBe12 ]
description: Based off of Hypixel's Housing, this plugin adds the core features of Hypixel Housing! It is the core functionality plugin that provides the custom functions, commands, and item editor players can use.
website: https://tommustbe12.com/
softdepend: [Citizens]

commands:
  house:
    description: Housing main command
    usage: /house
  edit:
    description: Edit the held item
    usage: /edit
  pos1:
    description: Set region position 1
    usage: /pos1
  pos2:
    description: Set region position 2
    usage: /pos2
